In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.linalg
import scipy.optimize as so
import scipy.stats as ss
import copy
import json


from tqdm import tqdm 
from matplotlib import cm
from matplotlib.ticker import LinearLocator

In [6]:
root = '/Users/Yannis/code/probabilistic_traffic_flow_modelling/'

In [23]:
data_fd = 'greenbergs'
inference_fd = 'underwoods'
ti = True
T = 30
N = 300000

root = '/Users/Yannis/code/probabilistic_traffic_flow_modelling/data/output/experiment_data/'
if ti:
    mcmc_file = root+f'{data_fd}_fd_log_simulation_n200/'+f"grwmh_{inference_fd}_model_{data_fd}_sim_learn_noise_n200/thermodynamic_integration/thermodynamic_integration_theta.txt"
else:
    mcmc_file = root+f'{data_fd}_fd_log_simulation_n200/'+f"grwmh_{inference_fd}_model_{data_fd}_sim_learn_noise_n200/theta.txt"

In [24]:
# Read mcmc chain data
chains = np.loadtxt(mcmc_file)

In [25]:
# Reshape
P = np.shape(chains)[1]
chains = chains.reshape((N,T,P))
print(f'N = {N}, T = {T}, P = {P}')

N = 300000, T = 30, P = 3


In [27]:
# Apply transformation
chain_transformed_mean = np.mean(chains,axis=0)
chain_mean = np.exp(chain_transformed_mean)

print(chain_mean)

[[ 7.98055904 13.01764389  0.0232363 ]
 [ 7.99347707 12.92742646  0.0217372 ]
 [ 7.89595574 12.99204837  0.02214315]
 [ 8.00358702 13.04220497  0.02417694]
 [ 7.92947481 13.00349497  0.02351779]
 [ 8.02058384 13.02182143  0.02445467]
 [ 7.86269364 13.03040504  0.02438237]
 [ 7.9434068  12.9795992   0.02315836]
 [ 8.02565128 13.04394922  0.02507381]
 [ 7.92820904 13.03531327  0.02515796]
 [ 7.9985806  13.09086556  0.02571348]
 [ 7.95190572 13.07051193  0.02601915]
 [ 7.98934727 13.08001546  0.02585283]
 [ 8.04886683 13.01030709  0.02654977]
 [ 7.9232717  13.08592979  0.02655481]
 [ 7.99442758 13.04980865  0.02781063]
 [ 7.9910694  13.03170116  0.02764359]
 [ 8.00380679 13.0397983   0.02834122]
 [ 7.9977686  13.03747761  0.02765554]
 [ 7.98247682 13.03637606  0.02859677]
 [ 7.97441294 13.05087013  0.02843055]
 [ 7.98765696 13.03846464  0.02781174]
 [ 7.98886287 13.03625853  0.02779252]
 [ 7.99021855 13.02844214  0.02755153]
 [ 7.98565414 13.0285561   0.02741887]
 [ 7.96994647 13.05474133